// <auto-generated />
using System;
using Crud1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crud1.Migrations
{
    [DbContext(typeof(MyDbcontext))]
    partial class MyDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crud1.Models.DowolnaKlasaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<string>("Nickname");

                    b.Property<int>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("Crud1.Models.DrugaKlasaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Age");

                    b.Property<int?>("DowolnaKlasaModelId");

                    b.Property<string>("Name");

                    b.Property<long>("Pesel");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("DowolnaKlasaModelId");

                    b.ToTable("Model2");
                });

            modelBuilder.Entity("Crud1.Models.DrugaKlasaModel", b =>
                {
                    b.HasOne("Crud1.Models.DowolnaKlasaModel")
                        .WithMany("DrugaKlasaModel")
                        .HasForeignKey("DowolnaKlasaModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
